apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetmanagement
  namespace: fleet-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetmanagement
  template:
    metadata:
      labels:
        app: fleetmanagement
    spec:
      containers:
        - name: fleetmanagement
          image: imaahmad/dotnet-training:latest
          ports:
            - containerPort: 5265
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "fms"
            - name: DB_USER
              value: "fleetuser"
            - name: DB_PASSWORD
              value: "fleetpassword"

---
apiVersion: v1
kind: Service
metadata:
  name: fleetmanagement-service
  namespace: fleet-namespace
spec:
  type: NodePort
  selector:
    app: fleetmanagement
  ports:
    - protocol: TCP
      port: 80             # External port (ClusterIP or LoadBalancer)
      targetPort: 5265   # Matches containerPort in Deployment
      nodePort: 30303
  # type: ClusterIP  # Use "LoadBalancer" if exposing externally