pipeline{
    agent any

    environment{
        DOCKER_IMAGE = 'imaahmad/fleetmanagement-dotnet-jenkins:latest'
        DB_HOST = ''
        DB_PORT = '3306'
        DB_NAME = 'fms'
        DB_USER = 'fleetuser'
        DB_PASSWORD = 'fleetpassword'
    }

    stages {
        stage('Clone Repository') {
            steps{
                git (
                    url: 'https://github.com/imaan942/training-dotnet.git',
                    credentialsId: 'git-credentials',
                    branch: 'main'
                )
            }
        }
        stage('Check Docker Version') {
            steps {
                sh 'docker --version'
            }
        }
        stage('Build docker image') {
            steps{
                script {
                    sh 'docker build -t $DOCKER_IMAGE -f fleetmanagement/Dockerfile .'
                }
            }
        }
        stage("Log in to docker hub") {
            steps{
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url:'https://index.docker.io/v1']){
                    sh 'echo "Logged into docker hub successfully"'
                }
            }
        }
        stage("Tag Docker Image") {
        steps {
            script {
            // Optionally, tag the image again (e.g., add 'latest' or another version tag)
            sh 'docker tag $DOCKER_IMAGE  $DOCKER_IMAGE'
            }
        }
    }
        stage("Push Image to docker hub") {
            steps{
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url:'https://index.docker.io/v1']){
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
    }
}